/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.client;

import java.awt.CardLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author RolfMoikjær
 */
public class Application extends javax.swing.JFrame implements Observer {

    ClientConnection cc;

    /**
     * Creates new form Application
     */
    public Application() {
        initComponents();

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                if (cc != null) {
                    cc.close();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewSwitch = new javax.swing.JPanel();
        authenticatePanel = new javax.swing.JPanel();
        btnAuthenticate = new javax.swing.JButton();
        responsePanel = new javax.swing.JPanel();
        lblResponse = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        viewSwitch.setLayout(new java.awt.CardLayout());

        authenticatePanel.setLayout(new java.awt.GridBagLayout());

        btnAuthenticate.setText("jButton1");
        btnAuthenticate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuthenticateActionPerformed(evt);
            }
        });
        authenticatePanel.add(btnAuthenticate, new java.awt.GridBagConstraints());

        viewSwitch.add(authenticatePanel, "authenticatePanel");

        lblResponse.setText("shower");

        javax.swing.GroupLayout responsePanelLayout = new javax.swing.GroupLayout(responsePanel);
        responsePanel.setLayout(responsePanelLayout);
        responsePanelLayout.setHorizontalGroup(
            responsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(responsePanelLayout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(lblResponse)
                .addContainerGap(269, Short.MAX_VALUE))
        );
        responsePanelLayout.setVerticalGroup(
            responsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(responsePanelLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(lblResponse)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        viewSwitch.add(responsePanel, "responsePanel");

        getContentPane().add(viewSwitch);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAuthenticateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuthenticateActionPerformed
        this.cc = new ClientConnection("localhost", 9090);
        this.cc.addObserver(this);
        Thread thread1 = new Thread(this.cc);
        thread1.start();

        CardLayout cardLayout = (CardLayout) this.viewSwitch.getLayout();
        cardLayout.show(this.viewSwitch, "responsePanel");
    }//GEN-LAST:event_btnAuthenticateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Application().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel authenticatePanel;
    private javax.swing.JButton btnAuthenticate;
    private javax.swing.JLabel lblResponse;
    private javax.swing.JPanel responsePanel;
    private javax.swing.JPanel viewSwitch;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        if (o.getClass().equals(ClientConnection.class)) {
            String response = (String) arg;
            lblResponse.setText(lblResponse.getText() + "\n" + response);
        }
    }
}
